name: Docker

on:
  push:
    branches:
      - develop
      - BECATRUE/31/deployment-test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup SSL certificates
      working-directory: wlm-ui
      run: |
        mkdir ssl
        echo "${{ secrets.FULLCHAIN_PEM }}" > ssl/fullchain.pem
        echo "${{ secrets.PRIVATE_KEY }}" > ssl/private.key
    - name: Sign in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker image
      working-directory: wlm-ui
      run: docker build -t ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}:latest .
    - name: Push Docker image to Docker Hub
      run: docker push ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}:latest
