name: ESLint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      working-directory: wlm-ui
      run: yarn install
    - name: Run ESLint
      working-directory: wlm-ui
      run: yarn eslint .
